### ISSUE TITLE
Quick start  recommends `svn co` from Github

### ISSUE THREAD

**Issue by tillea** [ncbi/pipelines#4]
Hi,
I have not tried the quick start guide but just from reading this line

     svn co https://github.com/ncbi/pipelines/trunk/amr_finder

will definitely fail.
Kind regards, Andreas.

**Comment by slottad** [comment]
This line has been tested many times, why do you believe it will not work?

It looks funky, but it is a workaround due to git not allowing pulling from a subdirectory, while svn does. GitHub supports a subversion translation for all repositories, so we use that to allow people to only get the relevant subdirectory.

We are considering moving amr_finder to its own repository, so this will no longer be necessary.

**Comment by tillea** [comment]
On Tue, Oct 09, 2018 at 07:54:28AM -0700, Douglas Slotta wrote:
> This line has been tested many times, why do you believe it will not work?
> 
> It looks funky, but it is a workaround due to git not allowing pulling from a subdirectory, while svn does. GitHub supports a subversion translation for all repositories, so we use that to allow people to only get the relevant subdirectory.
OK, now I tested and to my astonishment it really works.  Sorry for the noise but it looked like an cut-n-pasto from old docs.
 
> We are considering moving amr_finder to its own repository, so this will no longer be necessary. 
That would be helpful anyway.

Kind regards, Andreas.

**Comment by slottad** [comment]
No problem.
